### ISSUE TITLE
Infloeak scanner crashed

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#10]
When trying to solve the CSP issues reported by my initial scans, I made the infoleak scanner crash it seems.

As my "domain" is not always online, please see the curl output here:

```
$ curl -v http://skeeve.selfhost.eu
* Rebuilt URL to: http://skeeve.selfhost.eu/
*   Trying 78.49.227.218...
* TCP_NODELAY set
* Connected to skeeve.selfhost.eu (78.49.227.218) port 80 (#0)
> GET / HTTP/1.1
> Host: skeeve.selfhost.eu
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 21 Mar 2018 11:19:19 GMT
< Server: Apache/2.4.28 (Unix)
< Last-Modified: Wed, 21 Mar 2018 11:07:37 GMT
< ETag: "14d-567ea32de7040"
< Accept-Ranges: bytes
< Content-Length: 333
< Content-Security-Policy: default-src 'self'
< X-Content-Security-Policy: default-src 'self'
< X-WebKit-CSP: default-src 'self'
< Content-Type: text/html
<
<html>
<head>
 <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'">
  <meta http-equiv="X-Content-Security-Policy" content="default-src 'self'; script-src 'self'">
  <meta http-equiv="X-WebKit-CSP" content="default-src 'self'; script-src 'self'">
</head>
<body><h1>It works!</h1></body></html>
* Connection #0 to host skeeve.selfhost.eu left intact
```

**Comment by y-ates** [comment]
While http://skeeve.selfhost.eu is currently online, I can not reproduce your issue as the scanner prints the following:

```
{
    "name": "InfoLeak-Scanner",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "tests": [
        {
            "name": "CMS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "CMS_PLUGINS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        }
    ]
}
```

Is that domain on your local machine? Please note, that the scanner does not allow to scan localhost and other ports than port 80 or 443. In those cases it would not crash, but print an error message like "Scanning locahost is not allowed". This is not allowed because of security issues. If it would be allowed, the attacker could analyze IPs, services and similar which is not intended to be accesible on the internet. This attack is also known as Server Side Request Forgery (SSRF). 

I also tested it on my local machine, disabling the port and localhost checks and the scanner did just fine.

**Comment by Skeeve** [comment]
On 18-03-21 12:51, Yakup Ateş - notifications@github.com wrote:
> While http://skeeve.selfhost.eu is currently online, I can not reproduce your issue as the scanner prints the following:
>
> ```
> {
>      "name": "InfoLeak-Scanner",
>      "hasError": false,
>      "errorMessage": null,
>      "score": 100,
>      "tests": [
>          {
>              "name": "CMS",
>              "hasError": false,
>              "errorMessage": null,
>              "score": 100,
>              "scoreType": "info",
>              "testDetails": null
>          },
>          {
>              "name": "CMS_PLUGINS",
>              "hasError": false,
>              "errorMessage": null,
>              "score": 100,
>              "scoreType": "warning",
>              "testDetails": null
>          },
>          {
>              "name": "JS_LIB",
>              "hasError": false,
>              "errorMessage": null,
>              "score": 100,
>              "scoreType": "warning",
>              "testDetails": null
>          },
>          {
>              "name": "EMAIL_ADDRESS",
>              "hasError": false,
>              "errorMessage": null,
>              "score": 100,
>              "scoreType": "info",
>              "testDetails": null
>          },
>          {
>              "name": "PHONE_NUMBER",
>              "hasError": false,
>              "errorMessage": null,
>              "score": 100,
>              "scoreType": "info",
>              "testDetails": null
>          }
>      ]
> }
> ```
>
> Is that domain on your local machine? Please note, that the scanner does not allow to scan localhost and other ports than port 80 or 443. In those cases it would not crash, but print an error message like "Scanning locahost is not allowed". This is not allowed because of security issues. If it would be allowed, the attacker could analyze IPs, services and similar which is not intended to be accesible on the internet. This attack is also known as Server Side Request Forgery (SSRF).
>
> I also tested it on my local machine, disabling the port and localhost checks and the scanner did just fine.
>
It is on A local machine, but I'm not scanning "localhost" I simply 
registered http://skeeve.selfhost.eu on staging2.siwecos.de and ran a scan.

The scanners returned some issues I tried to fix changing apache config.

The next scan never returned results for Infoleak, DOMXSS and Header.

**Comment by y-ates** [comment]
Well, I don't know what the issue could be. But I doubt that it is an issue of the codebase of the InfoLeak-Scanner, as I could not reproduce it locally and with your given URL.

Also, running http://skeeve.selfhost.eu on https://staging2.siwecos.de/ returned:
```
Info Leak Scanner Mehr Informationen  
Letzter Scan: 2018-03-21 12:26:01
100
Überprüfung auf Erkennbarkeit des verwendeten CMS.Mehr Informationen
Überprüfung auf unsichere CMS-PluginsMehr Informationen
Überprüfung auf unsichere JavaScript-BibliothekenMehr Informationen
Überprüfung auf vorhandene Email-AdressenMehr Informationen
Überprüfung auf auslesbare TelefonnummernMehr Informationen
```

**Comment by Skeeve** [comment]
Seems it was a temporary issue and clearly indicates to me that we have to fix

https://github.com/SIWECOS/siwecos-core-api/issues/68

Sorry for bothering you…
