### ISSUE TITLE
No Error message

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#11]
Currently the core api does not receive an error when your scanner runs into issues like the domain is not reachable.

Currently we handle this with a timeout, but this is just a workaround.

Please provide, via callback, an error message to the core api.

An example could be (according to the api):

```JSON
[{
  "name": "ERROR",
  "hasError": true,
  "dangerlevel": 0,
  "errorMessage": {
    "placeholder": "NO_RESPONSE",
    "values": {
      "domain": "http://your.do.main",
    }
  },
  "score": 0,
  "scoreType": "success",
  "testDetails": []
}]
```

Check https://github.com/SIWECOS/siwecos-core-api/issues/68#issuecomment-378510683 for more information, especially about example values for the ERROR and NO_RESPONSE placeholders.

Please make sure to use error placeholders which are either specific for your scanner (like INFOLEAK_OUT_OF_MEMORY) if it is a scanner specific error message or, if the error is a general one which can happen to any scanner, non-specific (like NO_RESPONSE).

**Comment by y-ates** [comment]
The scanner does return errors, try e.g. a non existing URL and it should return something like this:

```
{
    "name": "InfoLeak-Scanner",
    "hasError": true,
    "errorMessage": "Sorry, the given address has no source code.",
    "score": 100,
    "tests": [
        {
            "name": "CMS",
            "hasError": true,
            "errorMessage": "Sorry, the given address has no source code.",
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "CMS_PLUGINS",
            "hasError": true,
            "errorMessage": "Sorry, the given address has no source code.",
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": true,
            "errorMessage": "Sorry, the given address has no source code.",
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": true,
            "errorMessage": "Sorry, the given address has no source code.",
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": true,
            "errorMessage": "Sorry, the given address has no source code.",
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        }
    ]
}
```

It would return the no source code error also if a timeout occured. I changed that just now and it will print:

```
{
    "name": "InfoLeak-Scanner",
    "hasError": true,
    "errorMessage": "Sorry, the given address is not reachable.",
    "score": 100,
    "tests": [
        {
            "name": "CMS",
            "hasError": true,
            "errorMessage": "Sorry, the given address is not reachable.",
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "CMS_PLUGINS",
            "hasError": true,
            "errorMessage": "Sorry, the given address is not reachable.",
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": true,
            "errorMessage": "Sorry, the given address is not reachable.",
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": true,
            "errorMessage": "Sorry, the given address is not reachable.",
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": true,
            "errorMessage": "Sorry, the given address is not reachable.",
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        }
    ]
}
```
for a timeout.
In your example, errorMessage contains a placeholder and values. Do you want me to change it?
And note that, the scanner will print the same errorMessage for every test if there was an error for the whole scanner (e.g. timeout).

You can see all possible errors in [README](https://github.com/SIWECOS/InfoLeak-Scanner#messages) below.

I am wondering why you don't receive any errors.

For the non existing site I used: asdkas.de
And for the timeout I used: kat.cr

**Comment by Skeeve** [comment]
1) The error message has to be a placeholder, according to the API and it can contain more placeholders like in the example I gave.
2) Maybe you return the error message as a reply to the start request instead of sending a callback?

**Comment by y-ates** [comment]
> The error message has to be a placeholder, according to the API and it can contain more placeholders like in the example I gave.

Okay, I will change that. 

> Maybe you return the error message as a reply to the start request instead of sending a callback?

I just tested it. It works just fine and sends the result correctly to the callback urls just like if there were no errors. It will send the exact same result as stated above to the callback urls.

**Comment by y-ates** [comment]
Done. The scanner will now print errors like this:

```
{
    "name": "InfoLeak-Scanner",
    "hasError": true,
    "errorMessage": {
        "placeholder": "NO_RESPONSE",
        "values": {
            "domain": "http://kat.cr"
        }
    },
    "score": 100,
    "tests": [
        {
            "name": "CMS",
            "hasError": true,
            "errorMessage": {
                "placeholder": "NO_RESPONSE",
                "values": {
                    "domain": "http://kat.cr"
                }
            },
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "CMS_PLUGINS",
            "hasError": true,
            "errorMessage": {
                "placeholder": "NO_RESPONSE",
                "values": {
                    "domain": "http://kat.cr"
                }
            },
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": true,
            "errorMessage": {
                "placeholder": "NO_RESPONSE",
                "values": {
                    "domain": "http://kat.cr"
                }
            },
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": true,
            "errorMessage": {
                "placeholder": "NO_RESPONSE",
                "values": {
                    "domain": "http://kat.cr"
                }
            },
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": true,
            "errorMessage": {
                "placeholder": "NO_RESPONSE",
                "values": {
                    "domain": "http://kat.cr"
                }
            },
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        }
    ]
}
```

All placeholders and their descriptions can be found here (including errors): [InfoLeak_Placeholders](https://github.com/SIWECOS/InfoLeak-Scanner/blob/master/doc/InfoLeak_Placeholders.txt) 

I will leave this issue open until you confirm that everything is good now, as I still don't know why you don't receive any errors.

**Comment by Skeeve** [comment]
Thanks for fixing the placeholders.

Regarding the callback: I only could look into the database. No results there.

Now I found the log and there I can see your callback.

So that part is upon the core.

**Comment by y-ates** [comment]
Alright then :).

**Comment by Weegy** [comment]
public static function getTimeOutArray( string $scanner ) {
		$timeout                                           = array();
		$timeout['name']                                   = 'TIMEOUT';
		$timeout['hasError']                               = true;
		$timeout['dangerlevel']                            = 0;
		$timeout['score']                                  = 0;
		$timeout['scoreType']                              = 'success';
		$timeout['testDetails']                            = array();
		$timeout['errorMessage']                           = array();
		$timeout['errorMessage']['placeholder']            = 'SCANNER_TIMEOUT';
		$timeout['errorMessage']['values']                 = array();
		$timeout['errorMessage']['values']['scanner']      = $scanner;
		$timeout['errorMessage']['values']['timeoutvalue'] = 300;
		return json_encode($timeout);

	}

**Comment by Skeeve** [comment]
Please see @Weegy's comment above. Your error message should be, according to the api, a "#/components/schemas/TranslateableMessage", not a string.

**Comment by Skeeve** [comment]
Ups…
Standby…
Seems @Weegy did not yet deploy your latest version.

**Comment by y-ates** [comment]
I think the output like (see above)

```
{
            "name": "JS_LIB",
            "hasError": true,
            "errorMessage": {
                "placeholder": "NO_RESPONSE",
                "values": {
                    "domain": "http://kat.cr"
                }
            },
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
}
```

is actually what it should be, right?
But I noticed 2 differences:
1. You are printing dangerlevel
2. The score is set to 0

Do you want me to change these e.g. return score 0 if an error occurs and print the given dangerlevel? If I should print dangerlevel, should it be in every test case or only in the result for the whole scanner (the first part)?
The API definition I got is this: https://app.swaggerhub.com/apis/SIWECOS/siwecos-scanner_api/0.0.1
Do you have something different?

If the current output is not like it should be, then please describe it a bit more detailed as I don't understand 

> Please see @Weegy's comment above. Your error message should be, according to the api, a "#/components/schemas/TranslateableMessage", not a string.

, because I am not printing a string.

**Comment by y-ates** [comment]
> Regarding dangerlevel

dangerlevel would be 0 for all test cases, I don't think it would change much. But if you want me to add it, I will.

> Regarding score=0

Okay, I will change that.

> Regading your message when a domain couldn't be reached

If a domain could not be reached "NO_RESPONSE" will be printed. In some cases (not many) the scanner does not receive source code, as the server does some anti measures for scanners or similar. Thus, the domain is reachable, but the scanner does not receive source code. So, I think this is a proper placeholder.

**Comment by Skeeve** [comment]
I agree with your view about "NO_SOURCE_CODE" vs. "NO_RESPONSE".

But for my domain you will get a "failed to connect", wenn you try to "curl" it. Means: "NO_RESPONSE"

But the error message I recieve from INFOLEAK (just tested) is "NO_SOURCE_CODE".

**Comment by Skeeve** [comment]
Trying your example with curl I get:

```
curl http://kat.cr
curl: (6) Could not resolve host: kat.cr; Der Name oder der Dienst ist nicht bekannt
```

So here a placeholder like "UNKNOWN_DOMAIN" would be more appropriate but you give "NO_RESPONSE".

**Comment by y-ates** [comment]
As you obviously wanted more specific connection errors, they are added now. As always these are listed and documented in [InfoLeak_Placeholders](https://github.com/SIWECOS/InfoLeak-Scanner/blob/master/doc/InfoLeak_Placeholders.txt).

Furthermore, the score will now drop to 0, if an error occurs.

Interestingly curl reports error code 6 for kat.cr in console and in PHP I get code 28, so that won't change as 28 stands for timeout.
