### ISSUE TITLE
Please disable CMS test

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#12]
As discussed on 2018-04-05, please disable the CMS test.

I fear no one told you so I'm opening this ticket.

**Comment by y-ates** [comment]
Are you sure about that? Why would you want me to disable that? My collegue said the CMS scan needs an improvement regarding false positives. This has been done.

**Comment by mniemietz** [comment]
The first step was to delete the scanner and to deploy a better version with less false positives. Afaik this has been done?

**Comment by y-ates** [comment]
The latest commits are fixing this. Moreover the scanner is now scanning for some more CMS:

- Drupal
- Joomla
- vbulletin
- Webspell
- Webspell-NOR
- Wordpress
- xt-commerce
- Contenido
- magento2
- shopsys
- shopify
- squarespace
- blogger
- 1C-Bitrix
- TYPO3
- prestashop

If you are still experiencing false-positives or similar, feel free to contact me.
