### ISSUE TITLE
Please use a user agent

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#14]
Please check: https://github.com/SIWECOS/siwecos-business-layer/issues/26

Since a configurable user agent is nothing we'll get in the near future, please check for example the HSHS/DOMXSS Scanner which uses a user-agent string. Your scan gets blocked by at least 2 customers because there is no valid user agent provided.

**Comment by y-ates** [comment]
The InfoLeak-Scanner does use user agents:

https://github.com/SIWECOS/InfoLeak-Scanner/blob/master/00_control/control.php#L335

**Comment by Skeeve** [comment]
This is strange. For https://www.sw-havixbeck.de your scanner never gets a result. When I curl that address, I get 403 unless I provide a(nother) Useragent.

Can you please verify the domain?

**Comment by y-ates** [comment]
Scanning the given address returns me the following:

```
{
    "name": "InfoLeak-Scanner",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "tests": [
        {
            "name": "CMS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "CMS_PLUGINS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": false,
            "errorMessage": null,
            "score": 98,
            "scoreType": "info",
            "testDetails": [
                {
                    "placeholder": "NUMBER_FOUND",
                    "values": {
                        "number": [
                            "02507 / 9395"
                        ]
                    }
                }
            ]
        }
    ]
}
```

Thus it is able to connect etc.

**Comment by Skeeve** [comment]
That's weird.

Maybe an intermittend problem.

To bad I don't know how to properly debug the scanners.

**Comment by y-ates** [comment]
Hmm. Could you explain the actual problem a bit more? What does "never gets a result" mean? Does it end in an endless loop, a timeout? What happens?

Also requesting that domain using curl I dont get a 403 or similar while I am not setting a user agent:

```
curl -v -s  https://www.sw-havixbeck.de > /dev/null
* Rebuilt URL to: https://www.sw-havixbeck.de/
* Hostname was NOT found in DNS cache
*   Trying 87.118.76.186...
* Connected to www.sw-havixbeck.de (87.118.76.186) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: CN=sw-havixbeck.de
* 	 start date: 2018-04-27 22:29:31 GMT
* 	 expire date: 2018-07-26 22:29:31 GMT
* 	 subjectAltName: www.sw-havixbeck.de matched
* 	 issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
* 	 SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: www.sw-havixbeck.de
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 17 May 2018 20:50:09 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.2.4
< P3P: CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"
< Expires: Wed, 17 Aug 2005 00:00:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: 8c418c6eb1ae15a946f5e0cbfbdb32ac=dmtkc3srnsr7db5dl5nb62mnqe; path=/; secure; HttpOnly
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< Last-Modified: Thu, 17 May 2018 20:50:09 GMT
< Vary: Accept-Encoding
< Strict-Transport-Security: max-age=63072000; includeSubDomains
< X-Powered-By: PleskLin
< 
{ [data not shown]
* Connection #0 to host www.sw-havixbeck.de left intact
```

**Comment by Weegy** [comment]
I just redeployed the scanner. If we want more verbosity I can help to implement the PaperTrail App.

Kind Regards

Marcel Wege
-----------------------------------------------------------------------------------------------------------------------------------------------------

[byte5]
byte5 digital media GmbH
Hanauer Landstraße 114, 60314 Frankfurt am Main

Tel +49-69-8700506-17, Fax +49-69-8700506-60
www.byte5.de<http://www.byte5.de/>, mwege@byte5.de<mailto:mwege@byte5.de>

HRB 79600, Amtsgericht Frankfurt am Main
Steuernummer 45 229 9867 9, Finanzamt Frankfurt am Main III
USt-IdNr. DE254183907

Umbraco Certified Gold Partner - Umbraco Core Contributor - Umbraco Trainer - uCommerce Power House

------------------------------------------------------------------------------------------------------------------------------------------------------

Von: Yakup Ateş [mailto:notifications@github.com]
Gesendet: Donnerstag, 17. Mai 2018 22:53
An: SIWECOS/InfoLeak-Scanner <InfoLeak-Scanner@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [SIWECOS/InfoLeak-Scanner] Please use a user agent (#14)


Hmm. Could you explain the actual problem a bit more? What does "never gets a result" mean? Does it end in an endless loop, a timeout? What happens?

Also requesting that domain using curl I dont get a 403 or similar while I am not setting a user agent:

curl -v -s  https://www.sw-havixbeck.de > /dev/null

* Rebuilt URL to: https://www.sw-havixbeck.de/

* Hostname was NOT found in DNS cache

*   Trying 87.118.76.186...

* Connected to www.sw-havixbeck.de<http://www.sw-havixbeck.de> (87.118.76.186) port 443 (#0)

* successfully set certificate verify locations:

*   CAfile: none

  CApath: /etc/ssl/certs

* SSLv3, TLS handshake, Client hello (1):

} [data not shown]

* SSLv3, TLS handshake, Server hello (2):

{ [data not shown]

* SSLv3, TLS handshake, CERT (11):

{ [data not shown]

* SSLv3, TLS handshake, Server key exchange (12):

{ [data not shown]

* SSLv3, TLS handshake, Server finished (14):

{ [data not shown]

* SSLv3, TLS handshake, Client key exchange (16):

} [data not shown]

* SSLv3, TLS change cipher, Client hello (1):

} [data not shown]

* SSLv3, TLS handshake, Finished (20):

} [data not shown]

* SSLv3, TLS change cipher, Client hello (1):

{ [data not shown]

* SSLv3, TLS handshake, Finished (20):

{ [data not shown]

* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384

* Server certificate:

*        subject: CN=sw-havixbeck.de

*        start date: 2018-04-27 22:29:31 GMT

*        expire date: 2018-07-26 22:29:31 GMT

*        subjectAltName: www.sw-havixbeck.de<http://www.sw-havixbeck.de> matched

*        issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3

*        SSL certificate verify ok.

> GET / HTTP/1.1

> User-Agent: curl/7.38.0

> Host: www.sw-havixbeck.de<http://www.sw-havixbeck.de>

> Accept: */*

>

< HTTP/1.1 200 OK

* Server nginx is not blacklisted

< Server: nginx

< Date: Thu, 17 May 2018 20:50:09 GMT

< Content-Type: text/html; charset=utf-8

< Transfer-Encoding: chunked

< Connection: keep-alive

< X-Powered-By: PHP/7.2.4

< P3P: CP="NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM"

< Expires: Wed, 17 Aug 2005 00:00:00 GMT

< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0

< Pragma: no-cache

< Set-Cookie: 8c418c6eb1ae15a946f5e0cbfbdb32ac=dmtkc3srnsr7db5dl5nb62mnqe; path=/; secure; HttpOnly

< X-Content-Type-Options: nosniff

< X-Frame-Options: SAMEORIGIN

< X-Xss-Protection: 1; mode=block

< Last-Modified: Thu, 17 May 2018 20:50:09 GMT

< Vary: Accept-Encoding

< Strict-Transport-Security: max-age=63072000; includeSubDomains

< X-Powered-By: PleskLin

<

{ [data not shown]

* Connection #0 to host www.sw-havixbeck.de<http://www.sw-havixbeck.de> left intact

**Comment by y-ates** [comment]
The given domain also works on siwecos.de for me (Letzter Scan: 17.05.2018 23:28). Which means that it returns the expected results.

**Comment by Skeeve** [comment]
On 18-05-18 00:31, Yakup Ateş - notifications@github.com wrote:
> The given domain also works on siwecos.de for me (Letzter Scan: 17.05.2018 23:28). Which means that it returns the expected results.
>
So I think the customer removed the blocking.

As we cannot reproduce the issue anymore and since I know, because I 
tested, that the customer blocked request without a useragent (and maybe 
with "outdated" useragents) maybe it's a good idea for every scanner to 
use the same useragent string.

**Comment by y-ates** [comment]
Yes, I agree with you here. All scanners should use the same user agent.

**Comment by y-ates** [comment]
As Chrome is the most used Browser at this moment and obviously Windows as its OS, I suggest the following user agent:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36`

Source: https://developers.whatismybrowser.com/useragents/explore/software_name/chrome/
