### ISSUE TITLE
control.php checkUrl buggy

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#18]
Ich habe zum Test mal control.php mit logs versehen:

```
error_log("URL pre: ".$this->url);
        $this->url = $this->checkURL($this->url);
error_log("URL post: ".$this->url);
```

Der Scan von https://cp.hornetsecurity.com zeigt, daß die URL "leer" zurückkommt. während andere URLs funktionieren.

```
[Thu Sep 20 09:36:13.972624 2018] [proxy_fcgi:error] [pid 48216:tid 139826007303936] [client 46.31.121.139:47804] AH01071: Got error 'PHP message: URL pre: https://cp.hornetsecurity.com\nPHP message: URL post: \n'


[Thu Sep 20 09:38:21.634207 2018] [proxy_fcgi:error] [pid 48217:tid 139826252924672] [client 46.31.121.139:47840] AH01071: Got error 'PHP message: URL pre: https://hradek.de\nPHP message: URL post: https://hradek.de\n'

```

**Comment by y-ates** [comment]
Probier mal folgendes:
`curl -I https://cp.hornetsecurity.com`
curl antwortetet darauf mit: 
`curl: (52) Empty reply from server`

und genau dazu kommt es auch im Scanner wenn der Header überprüft wird. Wenn ich checkURL ausschalte, läuft es durch ohne Fehler. Hast du irgendwelche Vorschläge?

**Comment by SniperSister** [comment]
Ich würde mal drauf tippen dass Hornet "ungewöhnliche" user agents auf firewall-level blockt - und curl ist nunmal kein normaler Browser.

**Comment by y-ates** [comment]
Der Header wird jetzt per GET geholt und löst das Problem.
Danke für die Vorschläge!

Fixed.

**Comment by Skeeve** [comment]
Ist das eine Fehlkonfiguration des Servers/der Firewall? Sollten wir das dann nicht als Scanergebnis mitliefern?

Alternativ: GET statt HEAD verwenden.

**Comment by SniperSister** [comment]
> Ist das eine Fehlkonfiguration des Servers/der Firewall? Sollten wir das dann nicht als Scanergebnis mitliefern?

Das Problem ist, dass es von diesen Fällen vermutlich dutzende verschiedene gibt, dafür extra Cases zu bauen lohnt sich imho nicht.
