### ISSUE TITLE
Regex Problem in 01_model/libs/analyser.php?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#2]
Braucht man in regulären Ausdrücken in Strings nicht 2 Backslashes? Also "\\s" und "\\[" etc.?

**Comment by Skeeve** [comment]
On 17-11-28 15:07, Yakup Ateş - notifications@github.com wrote:
>
> Hm, nicht das ich wüsste. Wäre mir zumindest neu. Läuft das bei dir so 
> nicht?
>
Noch nicht getestet. Ich kenne es von Beanshell und Java her, daß 
dummerweise alle \ verdoppelt werden müssen, weil einer immer schon 
durch den String "verloren" geht.

  https://books.google.de/books?id=6k7IfACN_P8C&pg=PA114&lpg=PA114&dq=php+regex+backslash&source=bl&ots=CqF9bQqo5M&sig=VFc_KjWveF8rXam90vNeFONr_f0&hl=de&sa=X&ved=0ahUKEwj8_b_GzOHXAhXGuxQKHQo9CY4Q6AEIczAJ#v=onepage&q=php%20regex%20backslash&f=false

legt mir nahe, daß dem wohl so ist. Aber ich kann mich irren. Ich 
verwende regex hauptsächlich in Perl und falle regelmäßig auf die Nase, 
wenn ich sie woanders verwende und die zusätzlichen \ vergesse ;)

**Comment by Skeeve** [comment]
On 17-11-28 15:07, Yakup Ateş - notifications@github.com wrote:
>
> Hm, nicht das ich wüsste. Wäre mir zumindest neu. Läuft das bei dir so 
> nicht?
>
Getestet. PHP verhält sich anders als erwartet, aber das ist gut ;) Ich 
muß mich nicht von PERL umgewöhnen.

Einzig, daß man ' und nicht " für die Strings nehmen sollte, weil man 
ansonsten "$" mit \ versehen muß.

**Comment by y-ates** [comment]
Super, dann wäre das ja geklärt ;-).
