### ISSUE TITLE
Übermittelten User-Agent verwenden

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#21]
Zukünftig wird seitens der Core-API ein User-Agent übermittelt.

Die Core-API sendet folgenden Input an die Scanner-URL:

```
{
  "url": "https://siwecos.de",
  "callbackurls": [
    "http://localhost:9002"
  ],
  "dangerLevel": 0,
  "userAgent": "USER_AGENT_ZUR_VERWENDUNG"
}
```

Dieser `userAgent` soll zum Aufrufen der zu scannenden Seite verwendet werden.

Sollte `userAgent` nicht gesetzt sein, so sollte der Scanner einen Standard verwenden, um verschiedene WAFs oder andere Sperrmaßnahmen umgehen und einen Scan erfolgreich durchführen zu können.

Ein Standard könnte bspw. folgender sein:

```
Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
```

Bitte Implementieren.

**Comment by Lednerb** [comment]
Siehe auch:
https://github.com/SIWECOS/siwecos-core-api/issues/158

**Comment by y-ates** [comment]
Dies ist bereits seit geraumer Zeit im InfoLeak-Scanner implementiert.
Siehe auch: https://github.com/SIWECOS/InfoLeak-Scanner#post

Zufälligerweise sogar mit der selben Bezeichnung "userAgent".

**Comment by Lednerb** [comment]
Perfekt, danke für die schnelle Rückmeldung.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 14. Nov. 2018, 00:00, Yakup Ateş schrieb:
