### ISSUE TITLE
Remove CMS and CMS version detection

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/InfoLeak-Scanner#22]
With the new scanner being almost ready, we should remove the less exact detectoin from the infoleak scanner

**Comment by Lednerb** [comment]
Das sollte jedoch lediglich erstmal in staging vorgenommen werden, bis der CMSVersion Scanner dann auch in `production` verfügbar ist.

@y-ates also bitte nicht auf `master` ändern, sondern dafür den `develop` branch verwenden und einmal mit @Weegy im slack Channel die Fragen bezüglich deployment klären.

**Comment by y-ates** [comment]
@SniperSister Does that also include the analysis of CMS Plugins? Or only CMS and CMS Version?

**Comment by SniperSister** [comment]
Only CMS and CMS versions

**Comment by y-ates** [comment]
DONE in branch "laravel"
