### ISSUE TITLE
Anpassung `name` Attribut

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#23]
Bisher nutzen alle Scanner Ihr Kürzel im `name` Attribut.

Sprich, der TLS-Scanner hat `"name": "TLS"`, der DOMXSS-Scanner `"name": "DOMXSS"`.

Der Einheitlichkeit halber sollte der InfoLeak-Scanner daher bspw. `INFOLEAK` nutzen.

--------------------

Dies vereinfacht die Handhabung der Übersetzungen im `translations` Repo sowie bei der Übersetzung selbst in der BLA.

**Comment by y-ates** [comment]
resolved by: 6c7dba1
