### ISSUE TITLE
Ausgabe LEAK_FOUND anpassen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#28]
Hohe Priorität da Abhängigkeit zu https://github.com/SIWECOS/siwecos-business-layer/issues/83

--------------------------

Scan der folgenden Seite: https://lucid-kare-92b7d9.netlify.com/
findet korrekterweise ein Leak. Die Formatierung ist jedoch falsch, sodass nicht korrekt übersetzt werden kann:

```
"testDetails": [
                    {
                        "placeholder": "EMAIL_FOUND",
                        "values": {
                            "email_adress": [
                                [
                                    "email@address.de"
                                ]
                            ]
                        }
                    }
                ]
```

Übersetzungs-Zeile:
```
'EMAIL_FOUND'                => "Die E-Mail-Adresse %email_adress% wurde gefunden. Wollen Sie diese E-Mail-Adresse wirklich veröffentlichen? Ein Angreifer kann diese bspw. für <a target=\"siwecos_wiki\" href=\"https://siwecos.de/wiki/Phishing\" title=\"Phishing\">Phishing</a>-Angriffe nutzen.",
```

Es kann also immer nur eine E-Mail Adresse übersetzt werden.
Außerdem macht das Sinn, dass wir mehrmals den Text ausgeben, wenn mehrere Adressen gefunden wurden.

----------------------------
Bitte Ausgabe wie folgt anpassen:

```
"testDetails": [
    {
           "placeholder": "EMAIL_FOUND",
           "values": {
             "email_adress": "email@address.de"
          }
    },
   {
           "placeholder": "EMAIL_FOUND",
           "values": {
             "email_adress": "andere@addresse.de"
          }
    }
]
```

Dann kann die Ausgabe wie hier abgebildet ausgegeben werden

![Bildschirmfoto vom 2019-04-01 13-42-51](https://user-images.githubusercontent.com/2056876/55325162-80831000-5484-11e9-845c-5f33f9038fc5.png)

----------------------

**Achtung: Bitte generell für alle Ausgabewerte übernehmen und schnellstmöglich umsetzen, da momentan keine Übersetzung vorgenommen werden kann**

-------------------

Momentan wird das dann wie folgt unschön dargestellt:

![Bildschirmfoto vom 2019-04-01 13-48-24](https://user-images.githubusercontent.com/2056876/55325299-e8395b00-5484-11e9-8f71-6fd70d7d2555.png)

**Comment by Lednerb** [comment]
7ba5c9b hat keine Änderungen an den Feldern für Telefonnummern etc. gebracht.

Bitte überprüfen und __NICHT__ auf `master` pushen, sondern auf `develop`.

`master` ersetzt jeweils die Version, die in `production` läuft.
Ein anderer Entwickler sollte über deine Änderungen einmal drüber  schauen, da diese prinzipiell alle Scans und Reports aller SIWECOS-Nutzer betreffen.

**Comment by y-ates** [comment]
Die Veränderungen sind in 6acad83 zu sehen. Aber in der tat habe ich die Telefonnummern vergessen - kommt in kürze. Der Rest sollte passen.

**Comment by Lednerb** [comment]
Done by #31
