### ISSUE TITLE
Lookahead oder  boundary verwenden in 01_model/libs/analyser.php

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#3]
Am Ende des Regex für email adressen steht [^w], um sicherzustellen, daß die TLD nicht Teil eines anderen Wortes ist.

Besser ist es hier, denke ich, einen lookahead zu verwenden, da man sich damit das Abschneiden im Nachgang sparen kann:

Positiv lookahead (?=\W)
Negative lookahead (?!=\w)

oder vielleicht einfach nur ein \b was auf Wortgrenzen matchen sollte.

**Comment by y-ates** [comment]
Ja, hast recht. Wird im neuen Regex beachtet, danke!
