### ISSUE TITLE
Anpassung errorMessage

### ISSUE THREAD

**Issue by y-ates** [SIWECOS/InfoLeak-Scanner#36]
Derzeitiger Stand (laravel):

```
            "errorMessage": {
                "placeholder": "CONNECT_ERROR",
                "values": {
                    "description": "cURL error 28: Operation timed out after 50000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
                }
            },
````

**Comment by Lednerb** [comment]
Folgendes Resultat:

```
{
    "name": "INFOLEAK",
    "version": "2.0.3",
    "hasError": true,
    "errorMessage": {
        "placeholder": "CONNECT_ERROR",
        "values": {
            "description": "cURL error 7: Failed to connect to gibt-es-nicht.de port 443: Connection refused (see http: //curl.haxx.se/libcurl/c/libcurl-errors.html)"
        }
    },
    "score": 0,
    "tests": [
        {
            "name": "CMS_PLUGINS",
            "hasError": true,
            "errorMessage": {
                "placeholder": "CONNECT_ERROR",
                "values": {
                    "description": "cURL error 7: Failed to connect to gibt-es-nicht.de port 443: Connection refused (see http: //curl.haxx.se/libcurl/c/libcurl-errors.html)"
                }
            },
            "score": 0,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": true,
            "errorMessage": {
                "placeholder": "CONNECT_ERROR",
                "values": {
                    "description": "cURL error 7: Failed to connect to gibt-es-nicht.de port 443: Connection refused (see http: //curl.haxx.se/libcurl/c/libcurl-errors.html)"
                }
            },
            "score": 0,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": true,
            "errorMessage": {
                "placeholder": "CONNECT_ERROR",
                "values": {
                    "description": "cURL error 7: Failed to connect to gibt-es-nicht.de port 443: Connection refused (see http: //curl.haxx.se/libcurl/c/libcurl-errors.html)"
                }
            },
            "score": 0,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": true,
            "errorMessage": {
                "placeholder": "CONNECT_ERROR",
                "values": {
                    "description": "cURL error 7: Failed to connect to gibt-es-nicht.de port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
                }
            },
            "score": 0,
            "scoreType": "info",
            "testDetails": null
        }
    ]
}
```

## Anmerkungen:

1. Wenn globales `hasError: true` und `errorMessage` gesetzt bedeutet dies, dass keine Tests durchgeführt werden konnten. Daher in diesem Fall leeres `tests` array zurückliefern.
2. `errorMessage.values` wird bei diesem Fehler nicht benötigt, da dies kein Platzhalter für die zu übersetzende Nachricht sein wird.
3. Sollte ein einzelner Test nicht durchgeführt werden können, so soll der `scoreType: failed` gesetzt werden (noch nicht in der [Dokumentation](https://github.com/SIWECOS/siwecos-core-api/tree/develop#each-testscoretype-attribute-string), wird gleich eingefügt)

**Comment by y-ates** [comment]
> errorMessage.values wird bei diesem Fehler nicht benötigt, da dies kein Platzhalter für die zu übersetzende Nachricht sein wird.

Es wird zwar nicht übersetzt, jedoch wurde es vorher gewünscht, dass man als Betreiber nachvollziehen kann was genau schief gegangen ist. 
Im Moment werden die verschiedenen Guzzle Fehler ausgegeben mit curl Fehlermeldungen etc. .
Wie soll hierbei verfahren werden?

**Comment by Lednerb** [comment]
Momentan haben wir ein ähnliches Problem in der BLA: https://github.com/SIWECOS/siwecos-business-layer/issues/120

Bis auf Weiteres, belass die Ausgaben mal in der Ausgabe des Scanners, bau die Fehlermeldungen aber nicht in den Übersetzungsdateien ein.

**Comment by Lednerb** [comment]
Aktuell gewünschte Handhabung:

1. Die Fehlermeldung wird vom Scanner mit zurückgeliefert. Dies kann via `description` Key geschehen.
2. In der Übersetzung soll der `:description` placeholder nicht verwendet werden

-----------------------

Ich schließe, da dies laut https://github.com/SIWECOS/InfoLeak-Scanner/issues/36#issuecomment-499680345 so realisiert ist.
