### ISSUE TITLE
"Neues" Ausgabeformat

### ISSUE THREAD

**Issue by y-ates** [SIWECOS/InfoLeak-Scanner#37]
Ausgabe entsprechend des "neuen" Ausgabeformats formulieren siehe [Scanner-Interface Dokumentation](https://github.com/SIWECOS/siwecos-core-api/tree/8c9995e325dedd688f271dcc792c736766ebee46#translatablemessage-object)

**Comment by y-ates** [comment]
Sollen die Ausgaben `node` und `node_content` bei Funden bezüglich JS_LIB oder CMS_PLUGIN ausgegeben werden?
Diese werden im Moment auch in den Texte eingebettet.

Es ist hilfreich für Leute, die dem jeweiligem Fund auf die Spur gehen möchten aber könnte zur Verwirrung bei anderen führen.

Beispiel derzeitiger Ausgabe:
```
            "name": "JS_LIB",
            "hasError": false,
            "errorMessage": null,
            "score": 96,
            "scoreType": "warning",
            "testDetails": [
                {
                    "translationStringId": "JS_LIB_VERSION",
                    "placeholders": {
                        "js_lib_name": "jquery",
                        "js_lib_version": "3.3.1",
                        "node": "src",
                        "node_content": "https://code.jquery.com/jquery-3.3.1.min.js"
                    }
                }
            ]
        }
```

**Comment by Lednerb** [comment]
Der Scanner sucht lediglich nach direkten Einbindungen auf der angegebenen URL, korrekt?

Also findet er JavaScript Bibliotheken zu 99% in `<script src="Bibliothek-URL"></script>` Tags.
Dann würde ich sagen, dass man auf die `node` Angaben verzichten kann.

Sucht der Scanner allerdings bspw. auch in komprimierten JavaScript Dateien oder nach Imports in .js und evtl. auch `.css` Dateien, wäre eine Angabe durchaus sinnvoll, *wo* die entsprechende Stelle gefunden wurde.

----------------------------------------

CC @Skeeve @ic0ns 

was meint ihr hierzu?

**Comment by Skeeve** [comment]
Schmerzt es, das drin zu lassen? Welcher Aufwanf ist es das rauszunehmen? Reicht auch ein verstecken (nicht-anzeigen) durch einen geänderten translationstring?

**Comment by y-ates** [comment]
Es raus zu nehmen ist kein besonderer Aufwand.
Es schmerzt jedoch auch nicht es drin zu lassen, insbesondere wenn der placeholder in den Ergebnissen nicht ausgegeben wird und dann quasi eh unsichtbar ist.

Ich denke, es einfach im Ausgegebenen Text nicht auszugeben sollte auch i.O. sein soweit gewünscht.
