### ISSUE TITLE
Regex findet nicht alle "kodierten" mailadressen in 01_model/libs/analyser.php

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#4]
Folgende Beispiele werden nicht vollständig erkannt:

    frank.schrank@gmx.net
    -> OK
    frank [dot] schrank [at] gmx [dot] net
                ^-- ab hier wird gefunden
    frank.schrank@mail.schrank.net
    -> OK
    frank [at] mail [dot] schrank [dot] net
    -> Wird gar nicht erkannt.

**Comment by Skeeve** [comment]
Vorschlag für einen neuen regex:

	# Beschreibung
	(?: # Local Part wie beschrieben auf https://de.wikipedia.org/wiki/E-Mail-Adresse
		[A-Za-z0-9!#$%&'*+\-\/=?^_`{|}~]
		|
		# Leerzeichen auch um "." nicht nur "[dot]" erlauben
		\s*
		(?:\.|\[dot\])
		\s*
		# Nicht implementiert, die Schreibweise mit "
	)+
	# Leerzeichen auch vor "@" nicht nur "[at]" erlauben
	\s*
	(?:@|\[at\])
	\s*
	# Domain Part 
	(?:
		(?:
			[A-Z]
			(?:[A-Z0-9-]*[A-Z0-9])?
			\s*
			(?:\.|\[dot\])
			\s*
		)
	)+
	(
		[A-Z]{2,}
	)
	\b
	
	# Code
	$local_part=  "(?:[A-Za-z0-9!#$%&'*+\\-\\/=?^_`{|}~]|\\s*(?:\\.|\\[dot\\])\\s*)+";
	$separator=   "\\s*(?:@|\\[at\\])\\s*";
	$domain_part= "(?:(?:[A-Z](?:[A-Z0-9-]*[A-Z0-9])?\\s*(?:\\.|\\[dot\\])\\s*))+([A-Z]{2,})\\b";
	$regex=       $local_part . $separator . $domain_part;

Hier sind die TLDs nicht eingebaut. Die könnten im Nachgang besser ausgefiltert werden, denke ich. Siehe den Kommentar im bisherigen Scanner im Bezug auf performance.

**Comment by y-ates** [comment]
Ja, das ist auf jeden Fall besser als der jetzige.

Ich habe gerade den folgenden:

```
# Local Part
(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:(\.|\s*\[dot\]\s*)
[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*
|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")

# Separator
(@|\s*\[at\]\s*)

# Domain Part
(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(\.|(\s*\[dot\]\s*)))+)([a-z]{2,})


# Nochmal alles zusammen für Copy&Paste
(?:[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:(\.|\s*\[dot\]\s*)[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")(@|\s*\[at\]\s*)(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(\.|(\s*\[dot\]\s*)))+)([a-z]{2,})
```

Hier müsste man dann die Domains auch später filtern. Aber ist das schneller es später per PHP auszufiltern?
Dieser regex ist auf jeden Fall schneller als dein Vorschlag. Was hälst du von dem?

**Comment by Skeeve** [comment]
Ohne es getestet zu haben: Es sieht inkorrekt aus.

Der Quote-Teil kann mit dem nicht-Quote Teil gemischt sein:

"Max Emanuel".Mustermann@...

Max."Mueller Luedenscheid"@…

Karl."der Grosse".Aachener@…

Und sollen wir echt nur um "[at]" und "[dot]" Leerzeichen erlauben oder auch um "." und "@"?

Was ist mit "[punkt]"? Keine Ahnung, ob das jemand verwendet, aber plausibel klingt es für deutsche Domains für mich.

**Comment by y-ates** [comment]
> Ohne es getestet zu haben: Es sieht inkorrekt aus.
> 
> Der Quote-Teil kann mit dem nicht-Quote Teil gemischt sein:
> 
> "Max Emanuel".Mustermann@...
> 
> Max."Mueller Luedenscheid"@…
> 
> Karl."der Grosse".Aachener@…
Ja, stimmt schon. Wäre aber eine doch sehr ungewöhnliche Kombination.

> Und sollen wir echt nur um "[at]" und "[dot]" Leerzeichen erlauben oder auch um "." und "@"?
Jup. Wäre ich für.

> Was ist mit "[punkt]"? Keine Ahnung, ob das jemand verwendet, aber plausibel klingt es für deutsche > Domains für mich.
"[punkt]" habe ich noch nie gesehen. Ich würde es erstmal raus lassen. Ist die Anzahl der Schritte die man extra machen muss wahrscheinlich nicht wert.

**Comment by Skeeve** [comment]
Anzahl der Schritte?

    \[dot\] -> \[(?:dot|punkt)\]

Soviel mehr ist's nicht.

Oder - just to confuse the Russians ;)

    \[(?:do|punk)t\]

**Comment by y-ates** [comment]
Ich werde [punkt] und (punkt) in den Regex aufnehmen. Ich habe nämlich eine Seite gefunden bei der es tatsächlich verwendet wurde [1].

[1]: https://www.thueringen.de/th6/tmwwdg/wirtschaft/wirtschaftsverwaltung/deregulierung/
