### ISSUE TITLE
Implementierung von Tests

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#43]
Dringend Unit-Tests implementieren, dann würden auch solche Fehler auffallen:

https://github.com/SIWECOS/InfoLeak-Scanner/blob/4746bdf1bd035ded487ae2ba050495a3d7afec22/app/InfoLeakScan.php#L70-L74

Du verwendest hier `$this->url` anstelle von `$url` bspw.

**Comment by Lednerb** [comment]
2 Tests schlagen fehl, so wird das bei Travis noch nicht durchlaufen:

```
laradock@2857efeef87b:/var/www/InfoLeak-Scanner$ phpunit
PHPUnit 7.5.10 by Sebastian Bergmann and contributors.

...FF.......                                                      12 / 12 (100%)

Time: 6.9 seconds, Memory: 22.00 MB

There were 2 failures:

1) Tests\Unit\HTTPTest::testPOST
Expected status code 200 but received 500.
Failed asserting that false is true.

/var/www/InfoLeak-Scanner/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:133
/var/www/InfoLeak-Scanner/tests/Unit/HTTPTest.php:64

2) Tests\Unit\HTTPTest::testDispatch_POST
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'OK'
+'{\n
+    "message": "Server Error"\n
laradock@2857efeef87b:/var/www/InfoLeak-Scanner$ phpunit
PHPUnit 7.5.10 by Sebastian Bergmann and contributors.

...FF.......                                                      12 / 12 (100%)

Time: 6.22 seconds, Memory: 22.00 MB

There were 2 failures:

1) Tests\Unit\HTTPTest::testPOST
Expected status code 200 but received 500.
Failed asserting that false is true.

/var/www/InfoLeak-Scanner/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:133
/var/www/InfoLeak-Scanner/tests/Unit/HTTPTest.php:64

2) Tests\Unit\HTTPTest::testDispatch_POST
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'OK'
+'{\n
+    "message": "Server Error"\n
+}'

/var/www/InfoLeak-Scanner/tests/Unit/HTTPTest.php:83

FAILURES!
Tests: 12, Assertions: 96, Failures: 2.
```

**Comment by Lednerb** [comment]
Außerdem ein Problem:
Die Tests laufen momentan nicht ohne gesetzten `APP_KEY`, sprich es muss eine `.env` vorhanden sein und der Key entsprechend gesetzt werden.

Bei allen anderen Laravel- basierten Projekten (CA, BLA, Version-Scanner, Header-Scanner) ist das aber problemlos ohne APP_KEY möglich. Bitte herausfinden warum das Problem hier auftritt und lösen.

**Comment by y-ates** [comment]
> 2 Tests schlagen fehl, so wird das bei Travis noch nicht durchlaufen
Läuft zum Zeitpunkt der Testdurchführung bereits redis?

**Comment by Lednerb** [comment]
Nein, da lief redis noch nicht.

Allerdings sollte das auch nicht notwendig sein, da du (ich nehme an das bezieht sich auf die Queue) mit `Queue::fake()` und `Queue::assertDispatched()` sicherstellen kannst, dass ein Job zur Queue hinzugefügt wird, ohne eine echte Queue-Abarbeitung im Test laufen zu lassen.

https://laravel.com/docs/5.8/mocking#queue-fake


Jobs kannst du auch einzeln testen, indem du einen Job anlegst und dann deren `->handle()` Funktion manuell ausführst. Bspw. so:

https://github.com/SIWECOS/siwecos-business-layer/blob/8f039941fda94168a76e1d8544151eadad4195dd/tests/Unit/StartScanJobTest.php#L41-L47


Wenn du bei deinem Test allerdings nicht anders kannst und dies unbedingt notwendig ist (was es wahrscheinlich nicht ist) dann kannst du auch den `QUEUE_DRIVER` auf `sync` stellen, wodurch die Queue direkt abgearbeitet wird (deaktiviert ist) und ebenfalls kein `redis` benötigt wird.

**Comment by y-ates** [comment]
> Außerdem ein Problem:
Die Tests laufen momentan nicht ohne gesetzten APP_KEY, sprich es muss eine .env vorhanden sein und der Key entsprechend gesetzt werden.


Wahrscheinlich nicht die beste Lösung, aber ich habe erstmal einfach default keys eingetragen.

> 2 Tests schlagen fehl, so wird das bei Travis noch nicht durchlaufen
Fixed. Dispatches werden auch mit einer fake Queue geprüft.
