### ISSUE TITLE
Config nutzen anstatt Dateien auszulesen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#45]
Bad practice, nicht an Laravel-Standard gehalten:

https://github.com/SIWECOS/InfoLeak-Scanner/blob/4746bdf1bd035ded487ae2ba050495a3d7afec22/app/Jobs/LeakJob.php#L65

**Comment by Lednerb** [comment]
Bitte die Konfiguration auch über Umgebungsvariablen steuerbar machen, siehe andere Scanner / Laravel-Standard config files.

Dies ist wichtig, wenn man bspw. über Docker bzw. `docker-compose` einen anderen Wert setzen möchte, ohne den Code zu editieren

**Comment by Lednerb** [comment]
@y-ates bei der Anpassung kannst du auch auf `\Config::get('STRING');` verzichten und den `config()` helper nutzen:

https://laravel.com/docs/5.8/helpers#method-config

**Comment by y-ates** [comment]
Ich bin mir nicht ganz sicher, wie wichtig es ist den default User-Agent über docker-compose einstellen zu können. Insbesondere, da man mit jedem Request durch Parameter den User-Agent sowieso setzen kann.

**Comment by Lednerb** [comment]
Unabhängig davon ist das eine einfache und schnelle Implementierung. Sollte noch kommen.

**Comment by Lednerb** [comment]
Wichtiger ist eher auch die anderen Config-Optionen zu setzen, damit diese gecached werden können, geht ja, soweit ich mich erinnere, nicht ausschließlich um den User-Agent String.
