### ISSUE TITLE
Bug mit ErrorHandling

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#49]
Beim Starten eines Scan-Auftrags mit nicht existenter Domain wird ein Fehler 500 geworfen.

Der Scanner antwortet nicht korrekt.
Sowohl callback als auch direkte Routine sind betroffen.

![Bildschirmfoto von 2019-05-13 11-26-00](https://user-images.githubusercontent.com/2056876/57618641-4e38f800-7584-11e9-8ac6-a4607e7d2572.png)

**Comment by y-ates** [comment]
Habe ich vorhin gefixt, ist durch die invalide JSON fix commits entstanden.
Bitte aktualisieren.

**Comment by Lednerb** [comment]
Korrekt.
