### ISSUE TITLE
Telefonnummern scanner korrekt in 01_model/libs/analyser.php ?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#5]
(Zeile 194) Potentielle Telefonnummern mit "-" werden verworfen.

Siehe eco.de - dort stehen Telefonnummern mit "-".

(Zeile 182) Potentielle Telefonnummern mit "x" werden verworfen.

"x" wird für eXtension (Durchwahl) verwendet https://answers.yahoo.com/question/index?qid=20120212191556AAL7hTQ

**Comment by y-ates** [comment]
> (Zeile 194) Potentielle Telefonnummern mit "-" werden verworfen.
> 
> Siehe eco.de - dort stehen Telefonnummern mit "-".

Die Potentielle Telefonnummer muss sowohl "-" als auch "." enthalten damit es verworfen wird.
Aus diesem Grund werden die Telefonnummern auf eco.de auch erkannt.

> (Zeile 182) Potentielle Telefonnummern mit "x" werden verworfen.
> 
> "x" wird für eXtension (Durchwahl) verwendet https://answers.yahoo.com/question/index?qid=20120212191556AAL7hTQ

Da hast du absolut Recht. Ich werde das beheben. Danke dafür!
