### ISSUE TITLE
False-Positive E-Mail gefunden

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#54]
Es wird vom Scanner der String `/publickey.mail@lednerb.eu` gefunden.
Dies ist ein False-Positive, der `/` kann kein Teil einer gültigen E-Mail Adresse sein.

![Bildschirmfoto von 2019-11-12 17-59-19](https://user-images.githubusercontent.com/2056876/68692691-30ba0a80-0576-11ea-9e06-7f55e48272e9.png)

**Comment by y-ates** [comment]
Den local part auf:

```
        $local_part  = "/(?:[a-z0-9\!\#\$\%&'*+=?^_`{|}~-]+(?:(\.|\s*(\[|\()(do|punk)t(\]|\))\s*)";
        $local_part .= "[a-z0-9\!\#\$\%&'*+\/=?^_`{|}~-]+)*|\"(?:[\x01-\x08\x0b\x";
        $local_part .= "0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x";
        $local_part .= "0c\x0e-\x7f])*\")";
```

ändern würde das Problem lösen.

Achtung: Habe nicht getestet, welche anderen Implikationen diese Veränderung bewirken würde.
