### ISSUE TITLE
Score-Berechnung InfoLeak-Scanner fehlerhaft

### ISSUE THREAD

**Issue by PetraStruck** [SIWECOS/InfoLeak-Scanner#56]
In der Darstellung der Testergebnisse scheint etwas schief zu laufen, siehe Screenshots:

![infoleak](https://user-images.githubusercontent.com/47851250/71557132-5033c680-2a42-11ea-99d9-f62d1ec82fe2.png)
![infoleak2](https://user-images.githubusercontent.com/47851250/71557136-5629a780-2a42-11ea-962a-8962a61e70f3.png)

Der Infoleak-Kreis zeigt nur 27%, aber es werden keine Fehler in den Ergebnissen verzeichnet.

Schau Dir bitte mal die Ergebnisse folgender Scans an:

569169,
569170,
569171,
569172,
569173,
569174,
569175,
569176,
569177,
569178,
569179

**Comment by Lednerb** [comment]
Letztes Ergebnis für diese Seite:

```
{
   "startedAt":"2020-01-06T07:21:42Z",
   "finishedAt":"2020-01-06T07:21:46Z",
   "name":"INFOLEAK",
   "version":"2.0.10",
   "hasError":false,
   "errorMessage":null,
   "score":20,
   "tests":[
      {
         "name":"CMS_PLUGINS",
         "hasError":false,
         "errorMessage":null,
         "score":100,
         "scoreType":"warning",
         "testDetails":null
      },
      {
         "name":"JS_LIB",
         "hasError":false,
         "errorMessage":null,
         "score":100,
         "scoreType":"warning",
         "testDetails":null
      },
      {
         "name":"EMAIL_ADDRESS",
         "hasError":false,
         "errorMessage":null,
         "score":100,
         "scoreType":"info",
         "testDetails":null
      },
      {
         "name":"PHONE_NUMBER",
         "hasError":false,
         "errorMessage":null,
         "score":100,
         "scoreType":"info",
         "testDetails":null
      }
   ]
}
```


Es werden jeweils 100er-Scores zurückgegeben, der Gesamt-Score liegt allerdings bei nur 20 Punkten und die `scoreTypes` sind falsch.

**Comment by PetraStruck** [comment]
Meine Frage wäre jetzt, was ich dem Kunden antworten kann. Wird der Fehler behoben und falls ja, wann und von wem?

**Comment by y-ates** [comment]
Der Fehler sollte nun behoben sein.

**Comment by PetraStruck** [comment]
Danke y-ates!
