### ISSUE TITLE
PHP-Datei mit MIME-Type PDF führt zu 0 Punkten

### ISSUE THREAD

**Issue by mniemietz** [SIWECOS/InfoLeak-Scanner#58]
Zitat Petra
`es geht um unsere Webseite xxxx Im seitlichen Menü findet sich ein Link auf den PHP-Skript xxx
 Dieser Skript sendet die PDF-Datei Terminplan.pdf an den Browser. Content-Type: application/pdf
 Content-Length: NN
 Der Info Leak Scanner scheint damit nicht zurecht zu kommen. Er gibt  lediglich die Überschrift und Null Punkte (rot) aus.`

**Comment by y-ates** [comment]
Zwecks Reproduzierbarkeit benötige ich ein konkreteres Beispiel. Gerne auch per Mail.

Wenn ich den Scanner auf eine Seite schmeiße die lediglich eine PDF zurückgibt, funktioniert das bei mir (Content-Type ist pdf etc.).

**Comment by y-ates** [comment]
Nicht reproduzierbar im InfoLeak-Scanner standalone.

**Comment by SniperSister** [comment]
Ein simpler Close finde ich hier nicht angebracht. Das löst ja das Problem des Kunden nicht?

**Comment by y-ates** [comment]
Auch siwecos.de gibt 100 Punkte zurück?

**Comment by SniperSister** [comment]
Wenn das so ist, ist ja alles in Ordnung. Dein Kommentar klang nach "lokal gehts, Rest egal". Das Problem war also einfach temporär und ist jetzt weg?

**Comment by y-ates** [comment]
Ich weiß nicht genau woran es lag. Nachdem ich die erforderlichen Daten zur Reproduzierbarkeit erhalten habe, wurde es meinerseits sowohl lokal als auch auf siwecos.de getestet. Keine Probleme, Scanner gibt 100 Punkte zurück.

**Comment by SniperSister** [comment]
Ok, dann kann Petra ja ein Feedback geben

**Comment by PetraStruck** [comment]
Kunden informiert.
