### ISSUE TITLE
Anpassung an die SIWECOS API

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/InfoLeak-Scanner#6]
Es gibt folgende Vorgaben, wie der Scanner arbeiten soll:
https://app.swaggerhub.com/apis/SIWECOS/siwecos-scanner_api/0.0.1

### Übergabeparameter
Dem Scanner werden folgende Werte per POST-Request an `/start` übergeben:

```
{
  "url": "string",
  "dangerLevel": 0,
  "callbackurls": [
    "string"
  ]
}
```
Die `url` wird gescannt. `dangerLevel` dürfte für den InfoLeak-Scanner nicht relevant sein.

### Callback
Der Scanner soll das Ergebnis an die übergebenen `callbackurls` per POST-Request senden.

### Ergebnis
Der Aufbau des zu sendenden Ergebnisses ist in der API-Spezifikation beschrieben.
Der TLS-Scanner hat dies bereits implementiert:
https://github.com/SIWECOS/WS-TLS-Scanner#results

**Comment by y-ates** [comment]
Okay. Da stellen sich mir aber ein paar Fragen:

1. Was ist denn `dangerLevel` bzw. was soll es genau angeben? Wenn es für den InfoLeak-Scanner nicht relevant ist, soll es dann alle Werte akzeptieren und einfach verwerfen oder einfach nur 0 akzeptieren?

2. Was für Fehler soll `hasError` und `errorMessage` angeben? Also Fehler die beim Test aufgetreten sind und dazu führten dass der Test nicht durchlaufen konnte?

3. Bei `testDetails` soll da bei `placeholder` das Thema des Scans aufgeführt werden und bei `values` entsprechend welche Werte getestet wurden? Bei den getesteten Werten würde dies zu einer sehr großen Auflistung führen. Soll es trotzdem aufgelistet werden? Oder ersetzten diese Felder die alten `comment` und `finding` Felder. Das heißt, dass bei `placeholder` die Sachen vom `comment` reinkommen und in `values` die von `finding`, aber eben etwas umformuliert und formatiert.

5. Der `ScanResult` gibt soweit ich es richtig verstehe eine Bewertung des gesamten Scans zurück und der `TestResult` das des individuellen. Soll dann beim `ScanResult` für `score` der Durchschnitt berechnet werden (ist wohl am sinnvollsten denke ich)? Andererseits werden die `score's` nun anscheinend in verschiedenen Kategorien aufgeteilt...

6. Was soll mit der GET Schnittstelle passieren? Soll es immernoch möglich sein den Scanner per GET anzusprechen? Und wenn dieser beibehalten werden soll, dann sollte die Ausgabe die der vom POST entsprechen nehme ich an.

**Comment by Lednerb** [comment]
1. `dangerLevel` wird beim TLS-Scanner eingesetzt, da es Tests gibt, die unter Umständen einen Server abschießen können. Am besten wäre es, der InfoLeak Scanner akzeptiert dann alle Werte. Sollte mal ein Test implementiert werden, der potentiell gefährlich ist, kann man da einen Schalter einbauen, dass manche Tests erst ab einem gewissen `dangerLevel` durchgeführt werden.

2. `hasError` auf `true` setzen, wenn ein Fehler aufgetreten ist. Bezüglich `errorMessage` kann eine Nachricht angegeben (string) werden, die übersetzbar sein sollte (die übersetzung findet dann in der SIWECOS-API statt)

3. Ich gehe von letzterem aus. Wie seht ihr das @SniperSister @Weegy @Skeeve ?

4. Das Interface bzw. die `ScanResult`-Vorgabe dient dazu, alle Scanner gleich und weitestgehend automatisiert in der API handhaben zu können. Ich denke bei deinem Scanner macht der Durchschnitt Sinn. Bei anderen Scannern gibt es so gravierende Findings, dass ein Durchschnitt sinnfrei wäre. (bspw. die Seite ist gehackt, aber 4 Tests sind erfolgreich, dann ist das gehackt ein `critical` error und es gibt einen Score von 0)

5. Die API wird den Scanner per POST ansprechen. GET könnte optional bleiben, deine Entscheidung.
Die Frage ist ob und inwieweit der Scanner außerhalb von SIWECOS genutzt wird (kann ja auch eigenständig betrieben werden). Definitiv sollten alle Endpunkte dokumentiert sein...

**Comment by SniperSister** [comment]
> Bei testDetails soll da bei placeholder das Thema des Scans aufgeführt werden und bei values entsprechend welche Werte getestet wurden? Bei den getesteten Werten würde dies zu einer sehr großen Auflistung führen. Soll es trotzdem aufgelistet werden? Oder ersetzten diese Felder die alten comment und finding Felder. Das heißt, dass bei placeholder die Sachen vom comment reinkommen und in values die von finding, aber eben etwas umformuliert und formatiert.

Beispiel:

`"testDetails" : [ {
      "placeholder" : "HACKED_FILES_FOUND",
      "values" : { "NUMBER": "2", "PATHS": "/images, /tmp" }
 } ]`

The language string would look like
`HACKED_FILES_FOUND="A total number of {{NUMBER}} hacked files have been found. The paths are: {{PATHS}}`
