### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#7]
Please check database for token 23 the sunbros domain is reported as completely wrong despite the fact that the page is almost empty.

At least no phone number nor an email address.

Score is reported as 0

```
[{
  "name": "CMS",
  "hasError": false,
  "errorMessage": null,
  "score": 0,
  "scoreType": "info",
  "testDetails": [null]
}, {
  "name": "CMS_PLUGINS",
  "hasError": false,
  "errorMessage": null,
  "score": 0,
  "scoreType": "warning",
  "testDetails": [null]
}, {
  "name": "JS_LIB",
  "hasError": false,
  "errorMessage": null,
  "score": 0,
  "scoreType": "warning",
  "testDetails": [null]
}, {
  "name": "EMAIL_ADDRESS",
  "hasError": false,
  "errorMessage": null,
  "score": 0,
  "scoreType": "info",
  "testDetails": [null]
}, {
  "name": "PHONE_NUMBER",
  "hasError": false,
  "errorMessage": null,
  "score": 0,
  "scoreType": "info",
  "testDetails": [null]
}]
```

**Comment by y-ates** [comment]
I didn't understand the issue fully. What do you mean with token 23 and which domain is the "sunbros domain"?

**Comment by Skeeve** [comment]
You need to look into the staging database for that.

But you understand the result?

  "hasError": false,

but

  "score": 0,

**Comment by y-ates** [comment]
> You need to look into the staging database for that.

Sorry, but I still don't know which staging database you are talking about, hehe.

> But you understand the result?
> "hasError": false,
> but
> "score": 0,

Oh, so if there were no findings it is considered as an error? Thus, the expected result would look like:

```
  "name": "PHONE_NUMBER",
  "hasError": true,
  "errorMessage": "No phone numbers found.",
  "score": 0,
  "scoreType": "info",
  "testDetails": [null]
```

and if "hasError": false
```
            "name": "PHONE_NUMBER",
            "hasError": false,
            "errorMessage": null,
            "score": 40,
            "scoreType": "info",
            "testDetails": [
                {
                    "placeholder": "NUMBER_FOUND",
                    "values": {
                        "number": [
                            "0123-10 00 22-2",
                            "0123-20 00 33-444"
                        ]
                    }
                }
            ]
        }
```


Or am I completely wrong now? I thought, the "hasError" is true if the scanner had troubles to scan for some reason. And if "hasError" is false and there were no findings the "score" would still be 0.

**Comment by Skeeve** [comment]
Please clarify with your colleagues about the exact meaning of each of the properties.

I'm not so clear myself. I just found 1 occurance of "hasError":true in the HeaderScanner, so maybe you are right.

"hasError" put aside: If you do not find a phone number, the score should be 100, ot 0, right? As the aim is to NOT find it, isn't it?

**Comment by SniperSister** [comment]
> And if "hasError" is false, so the scanner was able to scan and there were no findings the "score" would still be 0.

You get the full score if everything on your side is alright. So if you consider a phone number as a problem but can't find one in the markup, the score should be 100 and hasError should be false.

**Comment by y-ates** [comment]
> > And if "hasError" is false, so the scanner was able to scan and there were no findings the "score" would still be 0.
> 
> 
> You get the full score if everything on your side is alright. So if you consider a phone number as a problem but can't find one in the markup, the score should be 100 and hasError should be false.

Okay. And is `hasError: true`, if there were no findings but the scan has finished successfully (without results)? Would then `errorMessage` be something like `"errorMessage": "No phone numbers found."` as stated above?

**Comment by SniperSister** [comment]
hasError should be true if an *error* happens. An error is something that prevent's your scanner from returning proper (phone number found yes/no) result, i.e: connection refused, no markup returned, error 404 or 500 returned etc.

**Comment by Skeeve** [comment]
Closed? So it is fixed now?

**Comment by y-ates** [comment]
Yes, it is. Additionally the scoring in general is adjusted. See https://github.com/SIWECOS/InfoLeak-Scanner#score .

**Comment by Skeeve** [comment]
But it's not deployed, is it?

As the results of sunbros.de are still the same as before.

**Comment by y-ates** [comment]
For sunbros.de I get the following result:
```
{
    "name": "InfoLeak-Scanner",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "tests": [
        {
            "name": "CMS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "CMS_PLUGINS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "JS_LIB",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "warning",
            "testDetails": null
        },
        {
            "name": "EMAIL_ADDRESS",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        },
        {
            "name": "PHONE_NUMBER",
            "hasError": false,
            "errorMessage": null,
            "score": 100,
            "scoreType": "info",
            "testDetails": null
        }
    ]
}
```

This should be okay, shouldn't it?

**Comment by Skeeve** [comment]
On 18-03-14 10:17, Yakup Ateş - notifications@github.com wrote:
> This should be okay, shouldn't it?
Looks good to me. So seems to be not deployed yet.

Thanks.
