### ISSUE TITLE
Missing Placeholder values

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/InfoLeak-Scanner#9]
Please provide us with values for the placeholders your scanner uses.

The list of placeholders I currently know of is

```
    CMS_ONLY
    CMS_VERSION
    CMS_VERSION_VULN
    EMAIL_FOUND
    JS_LIB_ONLY
    JS_LIB_VERSION
    JS_LIB_VULN_VERSION
    NUMBER_FOUND
    PLUGIN_ONLY
```

Please add all placeholders I missed.

When providing us with the (german) text, please take your test results into account.

Please just send it as a plain text file or a fresh excel sheet - whatever you prefer. We will put it into our central gettext-file.

**Comment by y-ates** [comment]
All placeholders were already listed in: [README](https://github.com/SIWECOS/InfoLeak-Scanner#messages)

I translated those texts, you can find them here: [Placeholders with german text](https://github.com/SIWECOS/InfoLeak-Scanner/blob/master/doc/InfoLeak_Placeholders.txt)

Mentioning the node in which the finding was found and what content it had could be irrelevant for you, in that case feel free to adjust. Or tell me, so I will do it. Nevertheless the scanner will print those values.

**Comment by Skeeve** [comment]
Thanks a alot. Though I'm not sure the notation of the test-details placeholders (e.g. {cms}) is correct, this one is very much appreciated.

**Comment by y-ates** [comment]
You are welcome :).

Your notation could differ of course. As nothing was specified I simply picked something.

**Comment by y-ates** [comment]
Note: The German text has been updated.
